# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

cache: pip

matrix:
  include:
    # - python: 2.7
    #   env: TOXENV=py27
    # - python: 3.5
    #   env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

install:
  # - pip install -r requirements.txt
  - pip install tox codecov
  - pip list

script:
  # preparation
  - wget -c https://pjreddie.com/media/files/yolov3-tiny.weights -P ./weights --progress=bar:force:noscroll
  # testing
  - tox --sitepackages
  # installation
  #- pip install "pillow<7.0.0"  # this is temporal fix for some prd-party package issues
  #- pip install -r requirements.txt
  - pip install -e .
  # execution
  #- python scripts/run_detect.py --image_folder ./data/samples --model_def ./config/yolov3-tiny.cfg --weights_path ./weights/yolov3-tiny.weights --class_path ./data/coco.names --output_folder ./outputs
  #- python scripts/run_train.py --epochs 2 --batch_size 1 --model_def ./config/yolov3-tiny.cfg --path_output ./outputs --data_config ./config/custom.data --img_size 416

after_success: codecov

notifications:
  email: false
